{
  "login": "Jrfincham",
  "id": 10384525,
  "avatar_url": "https://avatars.githubusercontent.com/u/10384525?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Jrfincham",
  "html_url": "https://github.com/Jrfincham",
  "followers_url": "https://api.github.com/users/Jrfincham/followers",
  "following_url": "https://api.github.com/users/Jrfincham/following{/other_user}",
  "gists_url": "https://api.github.com/users/Jrfincham/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Jrfincham/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Jrfincham/subscriptions",
  "organizations_url": "https://api.github.com/users/Jrfincham/orgs",
  "repos_url": "https://api.github.com/users/Jrfincham/repos",
  "events_url": "https://api.github.com/users/Jrfincham/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Jrfincham/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Jason Robert Fincham",
  "company": "",
  "blog": "",
  "location": "",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2015-01-03T22:26:22Z",
  "updated_at": "2015-01-26T18:43:34Z"
}
